# see hooks/build and hooks/.config
FROM alpine

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

RUN echo "TARGETPLATFORM=$TARGETPLATFORM" && \
  echo "TARGETOS=$TARGETOS" && \
  echo "TARGETARCH=$TARGETARCH" && \
  echo "TARGETVARIANT=$TARGETVARIANT" && \
  echo "uname=$(uname -ar)" && \
  uname -ar > /uname.build && \
  apk --update add file
